### ISSUE TITLE
Furro

### ISSUE THREAD

**Issue by SergioHernandez25** [RichiiCD/first-code#1]
Hola buenas tardes, hoy día 25/03/2021 me yace una pregunta desde que ha empezado la tarde, cuando hoy usted y el señor maxylando habéis llegado más tarde de lo habitual se me ha formulado otra cuestión, y usted se preguntara que cuestión se le habrá formulado, tranquilo yo se la comento. Cuando te he visto se me pasado por la cabeza por que usted se ve tan furro, por favor hágaselo mirar. 
Y ya está, solamente quería transmitirle unos de mis pasamientos.

Saludos Master furro.
[https://www.google.com/search?q=furro&rlz=1C1GCEA_esES939ES939&tbm=isch&source=iu&ictx=1&fir=dHug955y4KCrXM%252CXCW0Ob-gzvuYRM%252C%252Fm%252F0lyd0&vet=1&usg=AI4_-kSQ_TRPV1mRDn-_UXKPajQasiDATA&sa=X&ved=2ahUKEwjE4rLz0cvvAhV09OAKHXPHAxYQ_B16BAguEAE#imgrc=dHug955y4KCrXM](url)

**Comment by RichiiCD** [comment]
ke
